Repository cybercongress/cyb-ts, pull requests merged in 2024-09, with the labels that each got.

#1275 fix(app): fixes
  src/components/containerGradient/Display/Display.module.scss
  src/components/ledger/stageActionBar.jsx
  src/containers/mint/index.tsx
  src/hocs/withIpfsAndKeplr.tsx
  src/pages/Social/Discord/Discord.tsx
  src/pages/Social/Social.tsx
  src/pages/Social/Telegram/Telegram.tsx
  src/pages/Social/Twitter/Twitter.tsx
  src/pages/oracle/landing/OracleLanding.tsx
  src/pages/robot/_refactor/account/actionBar.tsx
  src/pages/teleport/bridge/actionBar.bridge.tsx
  src/utils/search/utils.ts
Labels: error, feature

#1163 feat(cyberver)
  .env
  src/components/IconsNumber/IconsNumber.module.scss
  src/components/IconsNumber/IconsNumber.tsx
  src/components/account/account.tsx
  src/components/containerGradient/Display/Display.module.scss
  src/containers/Search/Filters/Filters.tsx
  src/containers/application/App.tsx
  src/containers/application/Header/CurrentApp/utils/findSelectAppByUrl.ts
  src/containers/portal/gift/ActionBarPortalGift.tsx
  src/containers/sigma/hooks/utils.js
  src/containers/sigma/index.tsx
  src/features/adviser/context.tsx
  src/features/cybernet/ui/pages/Delegates/Delegates.tsx
  src/features/cybernet/ui/pages/Delegates/DelegatesTable/DelegatesTable.tsx
  src/features/cybernet/ui/pages/Main/Main.tsx
  src/features/cybernet/ui/pages/Sigma/Sigma.tsx
  src/features/cybernet/ui/pages/Subnet/subnet.context.tsx
  src/features/cybernet/ui/pages/Subnet/tabs/SubnetNeurons/SubnetNeuronsTable/SubnetNeuronsTable.tsx
  src/features/cybernet/ui/pages/Subnet/tabs/Weights/WeightsTable/WeightsTable.tsx
  src/features/cybernet/ui/pages/Subnet/useCurrentSubnetGrades.tsx
  src/features/cybernet/ui/pages/Subnets/SubnetsTable/SubnetsTable.tsx
  src/features/passport/hooks/useCurrentPassport.tsx
  src/router.tsx
  src/utils/appsMenu/appsMenu.ts
Labels: feature, epic

#1296 feat(graph): cyberlinking
  src/features/cyberlinks/CyberlinksGraph/CyberlinksGraphContainer.tsx
  src/features/cyberlinks/GraphFullscreenBtn/GraphFullscreenBtn.module.scss
  src/features/cyberlinks/GraphFullscreenBtn/GraphFullscreenBtn.tsx
  src/features/cyberlinks/GraphNew/GraphNew.tsx
  src/features/cyberlinks/hooks/useCyberlink.ts
  src/features/ipfs/hooks/useAddToIPFS.ts
  src/hooks/dom/useEventListener.ts
  src/pages/oracle/Learn/Learn.tsx
  src/pages/robot/Brain/Brain.tsx
  src/pages/robot/Brain/ui/GraphView.tsx
  src/pages/robot/Brain/useGraphLimit.ts
Labels: feature

#1295 feat(graph): improvements
  src/features/cyberlinks/CyberlinksGraph/CyberlinksGraph.tsx
  src/features/cyberlinks/CyberlinksGraph/CyberlinksGraphContainer.tsx
  src/features/cyberlinks/GraphFullscreenBtn/GraphFullscreenBtn.module.scss
  src/features/cyberlinks/GraphFullscreenBtn/GraphFullscreenBtn.tsx
  src/features/cyberlinks/GraphNew/GraphNew.module.scss
  src/features/cyberlinks/GraphNew/GraphNew.tsx
  src/features/cyberlinks/graph/GraphActionBar/GraphActionBar.tsx
  src/features/cyberlinks/hooks/useCyberlink.ts
  src/layouts/Main.tsx
  src/pages/Brain/Brain.tsx
  src/pages/robot/Brain/Brain.tsx
  src/pages/robot/Brain/ui/GraphView.tsx
  src/pages/robot/Brain/useGraphLimit.ts
  src/pages/robot/Layout/Layout.tsx
Labels: feature

#1301 hotfix(app): commander autofocus
  src/layouts/Main.tsx
Labels: error

#1302 feat(keyboard): shortcuts page
  src/pages/Settings/Layout/SettingsMenu/SettingsMenu.tsx
  src/pages/Settings/Settings.tsx
  src/pages/robot/Hotkeys/Hotkeys.module.scss
  src/pages/robot/Hotkeys/Hotkeys.tsx
  src/pages/robot/Robot.tsx
Labels: feature

#1267 feat(studio)
  package.json
  src/components/Pill/Pill.module.scss
  src/components/Pill/Pill.tsx
  src/components/buttons/ButtonsGroup/ButtonsGroup.tsx
  src/components/containerGradient/Display/Display.module.scss
  src/components/link/cid.modules.scss
  src/components/link/link.tsx
  src/components/search/Spark/Meta/Links/Links.tsx
  src/containers/application/Header/Commander/Commander.tsx
  src/features/studio/ActionBar.tsx
  src/features/studio/Studio.module.scss
  src/features/studio/Studio.tsx
  src/features/studio/StudioWrapper.tsx
  src/features/studio/components/ControlPanel/ControlPanel.module.scss
  src/features/studio/components/ControlPanel/ControlPanel.stories.tsx
  src/features/studio/components/ControlPanel/ControlPanel.tsx
  src/features/studio/components/Editor/Editor.css
  src/features/studio/components/Editor/MilkdownEditor.tsx
  src/features/studio/components/Editor/feature/feature.ts
  src/features/studio/components/Editor/feature/placeholder/placeholder.ts
  src/features/studio/components/Editor/feature/shared.ts
  src/features/studio/components/Editor/hooks/useMilkdownEditor.ts
  src/features/studio/components/Editor/plugins/cybSyntax/pluginCybSyntax.ts
  src/features/studio/components/Editor/plugins/cybSyntax/remarkCybSyntax.ts
  src/features/studio/components/Editor/utils/slice.ts
  src/features/studio/components/Editor/utils/utils.ts
  src/features/studio/components/HistoryCommand/HistoryCommand.modules.scss
  src/features/studio/components/HistoryCommand/HistoryCommand.tsx
  src/features/studio/components/HistoryCommand/reload.png
  src/features/studio/components/KeywordButton/KeywordButton.module.scss
  src/features/studio/components/KeywordButton/KeywordButton.tsx
  src/features/studio/components/Keywords/Keywords.module.scss
  src/features/studio/components/Keywords/Keywords.tsx
  src/features/studio/studio.context.tsx
  src/features/studio/testData.js
  src/features/studio/utils/utils.ts
  src/hooks/useExecutionWithWaitAndAdviser.ts
  src/pages/teleport/components/Inputs/InputMemo/InputMemo.module.scss
  src/pages/teleport/components/Inputs/InputMemo/InputMemo.tsx
  src/router.tsx
  src/routes.ts
  src/services/neuron/neuronApi.ts
  src/utils/appsMenu/appsMenu.ts
  src/utils/appsMenu/images/studio.png
  yarn.lock
Labels: feature

#1307 fix(proposals): voting error, ui
  src/containers/governance/actionBarDatail.tsx
  src/containers/governance/proposalsDetail.tsx
Labels: error
