Repository cybercongress/cyb-ts, pull requests merged in 2024-01, with the labels that each got.

#1085 fix(send): history of send
  src/components/link/cid.modules.scss
  src/components/link/link.jsx
  src/pages/teleport/hooks/useGetSendTxsByAddressByLcd.tsx
  src/pages/teleport/send/components/dataSendTxs/DataSendTxsItems.tsx
Labels: error

#1077 fix(portal): vest citizens on claim
  src/containers/portal/ActionBarAddAvatar.tsx
  src/containers/portal/citizenship/index.tsx
  src/containers/portal/gift/ActionBarPortalGift.tsx
  src/containers/portal/gift/index.tsx
  src/containers/portal/gift/type.ts
  src/containers/portal/release/ActionBarRelease.tsx
  src/containers/portal/release/index.tsx
  src/containers/portal/release/type.d.ts
  src/containers/portal/utils.js
  src/containers/portal/utilsMsgs.ts
  src/containers/wasm/codes/actionBar.jsx
  src/containers/wasm/contract/ExecuteContract.tsx
  src/containers/wasm/contract/InstantiationContract.jsx
  src/containers/wasm/contract/RenderInstantiateMsg.jsx
  src/containers/wasm/contract/renderAbi/RenderAbiExecute.jsx
  src/contexts/signerClient.tsx
  src/soft.js/api/msgs.ts
Labels: priority

#1075 feat(sense): new sense 🧬
  src/components/Input/InputNumber/InputNumber.tsx
  src/components/account/Account.stories.tsx
  src/components/account/account.tsx
  src/components/containerGradient/Display/Display.module.scss
  src/components/contentIpfs/contentIpfs.tsx
  src/components/tooltip/Tooltip.module.scss
  src/containers/Search/Filters/Filters.tsx
  src/containers/portal/components/avataIpfs/AvataImgIpfs.tsx
  src/contexts/backend.tsx
  src/features/particles/utils.tsx
  src/features/sense/sense.redux.ts
  src/layouts/Main.module.scss
  src/layouts/Main.tsx
  src/pages/oracle/landing/OracleLanding.module.scss
  src/pages/robot/Layout/RobotMenu/RobotMenu.tsx
  src/pages/robot/Layout/useMenuCounts.tsx
  src/pages/robot/Robot.tsx
  src/pages/robot/Sense/ActionBar/ActionBar.tsx
  src/pages/robot/Sense/Sense.module.scss
  src/pages/robot/Sense/Sense.tsx
  src/pages/robot/Sense/SenseAdviser.context.tsx
  src/pages/robot/Sense/SenseButton/SenseButton.module.scss
  src/pages/robot/Sense/SenseButton/SenseButton.stories.tsx
  src/pages/robot/Sense/SenseButton/SenseButton.tsx
  src/pages/robot/Sense/SenseList/SenseList.module.scss
  src/pages/robot/Sense/SenseList/SenseList.tsx
  src/pages/robot/Sense/SenseList/SenseListFilters/SenseListFilters.tsx
  src/pages/robot/Sense/SenseList/SenseListItem/SenseListItem.container.tsx
  src/pages/robot/Sense/SenseList/SenseListItem/SenseListItem.module.scss
  src/pages/robot/Sense/SenseList/SenseListItem/SenseListItem.stories.tsx
  src/pages/robot/Sense/SenseList/SenseListItem/SenseListItem.tsx
  src/pages/robot/Sense/SenseViewer/Message/Message.container.tsx
  src/pages/robot/Sense/SenseViewer/Message/Message.module.scss
  src/pages/robot/Sense/SenseViewer/Message/Message.stories.tsx
  src/pages/robot/Sense/SenseViewer/Message/Message.tsx
  src/pages/robot/Sense/SenseViewer/SenseViewer.module.scss
  src/pages/robot/Sense/SenseViewer/SenseViewer.tsx
  src/pages/robot/Sense/_refactor/Date/Date.module.scss
  src/pages/robot/Sense/_refactor/Date/Date.stories.tsx
  src/pages/robot/Sense/_refactor/Date/Date.tsx
  src/pages/robot/Sense/_refactor/useParticleDetails.tsx
  src/pages/robot/Sense/_refactor/useSenseItem.tsx
  src/pages/robot/Sense/components/ParticleAvatar/ParticleAvatar.module.scss
  src/pages/robot/Sense/components/ParticleAvatar/ParticleAvatar.tsx
  src/pages/robot/Sense/types.ts
  src/pages/robot/Sense/useSenseSummary.tsx
  src/pages/robot/Sense/utils.tsx
  src/redux/reducers/index.ts
  src/redux/reducers/sense.ts
  src/routes.ts
  src/services/backend/types/sense.ts
Labels: priority, epic
